version: "3.1"

services:
  starwars_db:
    container_name: starwars_db
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    networks:
      - starwars_network

  starwars_api:
    container_name: starwars_api
    image: starwars_api
    depends_on:
      - starwars_db
    restart: always
    ports:
      - 9080:9080
    networks:
      - starwars_network
    environment:
      API_PORT: 9080
      MONGODB_URI: mongodb://starwars_db:27017/
      MONGODB_DATABASE_NAME: starwars
      MONGODB_TEST_DATABASE_NAME: starwars_testdb

networks:
  starwars_network:
